Commented out ossec agent deb pkg
Commented out the ossec agent deb package in the app servers host vars `install_files/ansible-base/host_vars/app.yml` to avoid an error.

When local_deb_packages is set to:

`install_files/ansible-base/host_vars/app.yml`

```
local_deb_packages:
  - securedrop-app-code-0.3-amd64.deb
  - securedrop-ossec-agent-2.8.1-amd64.deb
```

`install_files/ansible-base/roles/install_local_pkgs/tasks/main.yml `

```
- name: if defined install local deb packages
  apt: deb="/root/{{ item }}"
  with_items: local_deb_packages
```

I get the following error:

```
changed: [app-staging] => (item=securedrop-ossec-agent-2.8.1-amd64.deb) => {"changed": true, "dest": "/root/securedrop-ossec-agent-2.8.1-amd64.deb", "gid": 0, "group": "root", "item": "securedrop-ossec-agent-2.8.1-amd64.deb", "md5sum": "1cee8c780b4e37986ebb77d288a6e1fe", "mode": "0644", "owner": "root", "size": 446872, "src": "/home/vagrant/.ansible/tmp/ansible-tmp-1422303994.46-46385956698306/source", "state": "file", "uid": 0}

TASK: [install_local_pkgs | if defined install local deb packages] ************
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE apt deb="/root/securedrop-app-code-0.3-amd64.deb,securedrop-ossec-agent-2.8.1-amd64.deb"
<127.0.0.1> EXEC ['ssh', '-C', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=600s', '-o', 'ConnectTimeout=60', '-o', 'ControlPath=/home/dolo/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2200', '-o', 'IdentityFile="/home/dolo/.vagrant.d/insecure_private_key"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=60', '127.0.0.1', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=xzdzunzdobrwcaethcahjwyzsfetjubj] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-xzdzunzdobrwcaethcahjwyzsfetjubj; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python\'"\'"\'\'']
failed: [app-staging] => (item=securedrop-app-code-0.3-amd64.deb,securedrop-ossec-agent-2.8.1-amd64.deb) => {"failed": true, "item": "securedrop-app-code-0.3-amd64.deb,securedrop-ossec-agent-2.8.1-amd64.deb", "parsed": false}
invalid output was: SUDO-SUCCESS-xzdzunzdobrwcaethcahjwyzsfetjubj
Traceback (most recent call last):
  File "<stdin>", line 1907, in <module>
  File "<stdin>", line 523, in main
  File "<stdin>", line 299, in install_deb
  File "/usr/lib/python2.7/dist-packages/apt/debfile.py", line 61, in __init__
    self.open(filename)
  File "/usr/lib/python2.7/dist-packages/apt/debfile.py", line 70, in open
    self._debfile = apt_inst.DebFile(self.filename)
SystemError: E:Could not open file securedrop-ossec-agent-2.8.1-amd64.deb - open (2: No such file or directory), E:Unable to determine file size for fd -1 - fstat (9: Bad file descriptor), E:Read error - read (9: Bad file descriptor)
```

I only get the error when local_deb_packages is a list, when one package or the other is commented out it works fine